#!/usr/bin/env bash
#
# First app boot: generate .env.production, db:prepare, assets:precompile, start Rails server.
# Run after bootstrap_runtime.sh and exec $SHELL.
# From repo root: bash deploy/first_app_boot.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
SERVER_DIR="$REPO_ROOT/server"
ENV_FILE="$SERVER_DIR/.env.production"

if [[ ! -d "$SERVER_DIR" ]]; then
  echo "ERROR: server directory not found: $SERVER_DIR"
  exit 2
fi

cd "$SERVER_DIR"

# Ensure rbenv is available (in case first_app_boot is run in a new shell)
RBENV_ROOT="${RBENV_ROOT:-$HOME/.rbenv}"
export PATH="$RBENV_ROOT/bin:$RBENV_ROOT/shims:${PATH}"
eval "$("$RBENV_ROOT/bin/rbenv" init - bash 2>/dev/null)" 2>/dev/null || true

# Generate SECRET_KEY_BASE and write .env.production
SECRET_KEY_BASE=$(bundle exec rails secret 2>/dev/null || openssl rand -hex 64)
cat > "$ENV_FILE" <<EOF
# Generated by deploy/first_app_boot.sh
RAILS_ENV=production
SECRET_KEY_BASE=$SECRET_KEY_BASE
DB_ADAPTER=mysql2
EOF
echo "[first_boot] Wrote $ENV_FILE with generated SECRET_KEY_BASE"

export RAILS_ENV=production
export SECRET_KEY_BASE

echo "[first_boot] Running db:prepare..."
bundle exec rails db:prepare

echo "[first_boot] Running assets:precompile..."
bundle exec rails assets:precompile

echo "[first_boot] Starting Rails server on http://0.0.0.0:3000 ..."
exec bundle exec rails server -b 0.0.0.0 -p 3000
